# Configuracoes de Rede
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 5001

# Timeouts (segundos)
HEARTBEAT_INTERVAL = 2.0
HEARTBEAT_TIMEOUT = 5.0
ELECTION_TIMEOUT = 3.0
REQUEST_TIMEOUT = 2.0

# Power Score
MIN_POWER_SCORE = 10
MAX_POWER_SCORE = 100
